# screen dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# colors (R,G,B)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (100, 100, 100)

# game title
GAME_TITLE = "ASTEROIDS CLONE"

# game states
GAME_STATE_MENU  = "MENU"
GAME_STATE_PLAYING = "PLAYING"
